// Code generated by Arduino IoT Cloud, DO NOT EDIT.
/*If you are running the main code on arduino iot you don't need this file just copy past the code in the main file*/

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "0711f295-5473-46e6-8f73-21ac237425bc";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float humidity;
float soil_moisture;
float temperature;
float water_flow;
float water_level;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(soil_moisture, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(water_flow, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(water_level, READ, ON_CHANGE, NULL, 1);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
"
